### ISSUE TITLE
p5 processing js

### ISSUE THREAD

**Issue by Lewiscowles1986** [mpwelton/lissajous#1]
```
let maxTheta;
let freqMod;
let freqX1;
let freqX2;
let freqX3;
let freqX4;
let freqY1;
let freqY2;
let freqY3;
let freqY4;
let freqZ1;
let freqZ2;
let freqZ3;
let freqZ4;
let vol01;
let vol02;
let vol03;
let vol04;
let lfo01;
let lfo02;
let lfo03;
let lfo04;
let noise;
let maxWeight;
let thetaIncrement;

function setup() {
 
  maxTheta = 140;
  freqMod = 36000;
  freqX1 = 2.0;
  freqX2 = 2.0;
  freqX3 = 2.0;
  freqX4 = 2.0;
  freqY1 = 3.0;
  freqY2 = 3.0;
  freqY3 = 3.0;
  freqY4 = 3.0;
  freqZ1 = 1.0;
  freqZ2 = 1.0;
  freqZ3 = 1.0;
  freqZ4 = 1.0; 
  vol01 = 0.25;
  vol02 = 0.25;
  vol03 = 0.25;
  vol04 = 0.25;
  lfo01 = 8.9;
  lfo02 = 9.1;
  lfo03 = 9.3;
  lfo04 = 9.5;
  noise = 0.005;
  maxWeight = 2;
  thetaIncrement = 0.02;
 
  //fullScreen(P3D);
  createCanvas(1080, 1080, WEBGL);  
 
  blendMode(REPLACE);
 
}

function draw() {
 
  translate(width/2, height/2);
 
  beginShape();            
 
  background(0, 0, 0);
   
 noFill();
    
   for (let theta = 0; theta <= maxTheta * (PI * 2); theta +=thetaIncrement) {
   
    let phaseX1 = PI * (2.0 + (sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseX2 = PI * (2.0 + (sin(radians(frameCount / PI) + 1) / 2) * 2);    
    let phaseX3 = PI * (2.0 + (cos(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseX4 = PI * (2.0 + (cos(radians(frameCount / PI) + 1) / 2) * 2);    

    let phaseY1 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseY2 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseY3 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseY4 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);
    
    let phaseZ1 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseZ2 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseZ3 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseZ4 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);      
    
    let ampX1 = width * 0.12;
    let ampX2 = width * 0.12;
    let ampX3 = width * 0.12;
    let ampX4 = width * 0.12;      
   
    let ampY1 = height * 0.12;
    let ampY2 = height * 0.12;
    let ampY3 = height * 0.12;    
    let ampY4 = height * 0.12;
    
    //let ampZ1 = height * 0.12;
    //let ampZ2 = height * 0.12;
    //let ampZ3 = height * 0.12;    
    //let ampZ4 = height * 0.12;
    
    let ampZ1 = (height * vol01) * ((sin(radians(frameCount / lfo01)) + 1) / 2);
    let ampZ2 = (height * vol02) * ((sin(radians(frameCount / lfo02)) + 1) / 2);
    let ampZ3 = (height * vol03) * ((sin(radians(frameCount / lfo03)) + 1) / 2);
    let ampZ4 = (height * vol04) * ((sin(radians(frameCount / lfo04)) + 1) / 2);    
    
    //let totalAmp = (amp01 + amp02 + amp03 + amp04);
    //let volumeMultiplier = totalAmp / (height * 0.9);
    //let newAmp01 = amp01 / volumeMultiplier;
    //let newAmp02 = amp02 / volumeMultiplier;
    //let newAmp03 = amp03 / volumeMultiplier;
    //let newAmp04 = amp04 / volumeMultiplier;
        
    let x = ((sin((theta * ((freqX1 + noise) * sin(radians(theta) / freqMod))) + phaseX1) * ampX1) + (sin((theta * (freqX2 + noise)) + phaseX2) * ampX2) + (sin((theta * (freqX3 + noise)) + phaseX3) * ampX3) + (sin((theta * (freqX4 + noise)) + phaseX4) * ampX4));
    let y = ((sin((theta * ((freqY1 + noise) * sin(radians(theta) / freqMod))) + phaseY1) * ampY1) + (sin((theta * (freqY2 + noise)) + phaseY2) * ampY2) + (sin((theta * (freqY3 + noise)) + phaseY3) * ampY3) + (sin((theta * (freqY4 + noise)) + phaseY4) * ampY4));    
    let z = ((sin((theta * ((freqZ1 + noise) * sin(radians(theta) / freqMod))) + phaseZ1) * ampZ1) + (sin((theta * (freqZ2 + noise)) + phaseZ2) * ampZ2) + (sin((theta * (freqZ3 + noise)) + phaseZ3) * ampZ3) + (sin((theta * (freqZ4 + noise)) + phaseZ4) * ampZ4));    
    
    colorMode(RGB, 255, 255, 255, 100);
    
    //strokeWeight(3);
    strokeWeight(map(theta, 0, maxTheta, 1, maxWeight));
        
    //let red = map(sin(radians(frameCount)), -1, 1, 192, 255);
    //let green = map(sin(radians(frameCount) + 45), -1, 1, 192, 255);
    //let blue = map(sin(radians(frameCount) + 90), -1, 1, 192, 255);
    
    let colVal01 = map(x, 0, (height * 0.4), 128, 255); 
    let colVal02 = map(y, 0, (height * 0.4), 128, 255);
    let colVal03 = map(z, 0, (height * 0.4), 128, 255);
    
    //stroke(255, 255, 128);
    stroke(colVal01, colVal02, colVal03);
    
    point(x, y, z);
    
  }
 
  endShape();
 
}
```

seems to be roughly equivalent to https://github.com/mpwelton/lissajous/blob/main/Lissajous_Generator_FULL_VERSION.pde

**Comment by mpwelton** [comment]
That's great - thanks.
    On Monday 29 April 2024 at 19:51:49 BST, Lewis Cowles ***@***.***> wrote:  
 
 

let maxTheta;
let freqMod;
let freqX1;
let freqX2;
let freqX3;
let freqX4;
let freqY1;
let freqY2;
let freqY3;
let freqY4;
let freqZ1;
let freqZ2;
let freqZ3;
let freqZ4;
let vol01;
let vol02;
let vol03;
let vol04;
let lfo01;
let lfo02;
let lfo03;
let lfo04;
let noise;
let maxWeight;
let thetaIncrement;

function setup() {
 
  maxTheta = 140;
  freqMod = 36000;
  freqX1 = 2.0;
  freqX2 = 2.0;
  freqX3 = 2.0;
  freqX4 = 2.0;
  freqY1 = 3.0;
  freqY2 = 3.0;
  freqY3 = 3.0;
  freqY4 = 3.0;
  freqZ1 = 1.0;
  freqZ2 = 1.0;
  freqZ3 = 1.0;
  freqZ4 = 1.0; 
  vol01 = 0.25;
  vol02 = 0.25;
  vol03 = 0.25;
  vol04 = 0.25;
  lfo01 = 8.9;
  lfo02 = 9.1;
  lfo03 = 9.3;
  lfo04 = 9.5;
  noise = 0.005;
  maxWeight = 2;
  thetaIncrement = 0.02;
 
  //fullScreen(P3D);
  createCanvas(1080, 1080, WEBGL);  
 
  blendMode(REPLACE);
 
}

function draw() {
 
  translate(width/2, height/2);
 
  beginShape();            
 
  background(0, 0, 0);
   
 noFill();
    
   for (let theta = 0; theta <= maxTheta * (PI * 2); theta +=thetaIncrement) {
   
    let phaseX1 = PI * (2.0 + (sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseX2 = PI * (2.0 + (sin(radians(frameCount / PI) + 1) / 2) * 2);    
    let phaseX3 = PI * (2.0 + (cos(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseX4 = PI * (2.0 + (cos(radians(frameCount / PI) + 1) / 2) * 2);    

    let phaseY1 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseY2 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseY3 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseY4 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);
    
    let phaseZ1 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseZ2 = (PI * 0.5) + ((sin(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseZ3 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);
    let phaseZ4 = (PI * 0.5) + ((cos(radians(frameCount / PI) + 1) / 2) * 2);      
    
    let ampX1 = width * 0.12;
    let ampX2 = width * 0.12;
    let ampX3 = width * 0.12;
    let ampX4 = width * 0.12;      
   
    let ampY1 = height * 0.12;
    let ampY2 = height * 0.12;
    let ampY3 = height * 0.12;    
    let ampY4 = height * 0.12;
    
    //let ampZ1 = height * 0.12;
    //let ampZ2 = height * 0.12;
    //let ampZ3 = height * 0.12;    
    //let ampZ4 = height * 0.12;
    
    let ampZ1 = (height * vol01) * ((sin(radians(frameCount / lfo01)) + 1) / 2);
    let ampZ2 = (height * vol02) * ((sin(radians(frameCount / lfo02)) + 1) / 2);
    let ampZ3 = (height * vol03) * ((sin(radians(frameCount / lfo03)) + 1) / 2);
    let ampZ4 = (height * vol04) * ((sin(radians(frameCount / lfo04)) + 1) / 2);    
    
    //let totalAmp = (amp01 + amp02 + amp03 + amp04);
    //let volumeMultiplier = totalAmp / (height * 0.9);
    //let newAmp01 = amp01 / volumeMultiplier;
    //let newAmp02 = amp02 / volumeMultiplier;
    //let newAmp03 = amp03 / volumeMultiplier;
    //let newAmp04 = amp04 / volumeMultiplier;
        
    let x = ((sin((theta * ((freqX1 + noise) * sin(radians(theta) / freqMod))) + phaseX1) * ampX1) + (sin((theta * (freqX2 + noise)) + phaseX2) * ampX2) + (sin((theta * (freqX3 + noise)) + phaseX3) * ampX3) + (sin((theta * (freqX4 + noise)) + phaseX4) * ampX4));
    let y = ((sin((theta * ((freqY1 + noise) * sin(radians(theta) / freqMod))) + phaseY1) * ampY1) + (sin((theta * (freqY2 + noise)) + phaseY2) * ampY2) + (sin((theta * (freqY3 + noise)) + phaseY3) * ampY3) + (sin((theta * (freqY4 + noise)) + phaseY4) * ampY4));    
    let z = ((sin((theta * ((freqZ1 + noise) * sin(radians(theta) / freqMod))) + phaseZ1) * ampZ1) + (sin((theta * (freqZ2 + noise)) + phaseZ2) * ampZ2) + (sin((theta * (freqZ3 + noise)) + phaseZ3) * ampZ3) + (sin((theta * (freqZ4 + noise)) + phaseZ4) * ampZ4));    
    
    colorMode(RGB, 255, 255, 255, 100);
    
    //strokeWeight(3);
    strokeWeight(map(theta, 0, maxTheta, 1, maxWeight));
        
    //let red = map(sin(radians(frameCount)), -1, 1, 192, 255);
    //let green = map(sin(radians(frameCount) + 45), -1, 1, 192, 255);
    //let blue = map(sin(radians(frameCount) + 90), -1, 1, 192, 255);
    
    let colVal01 = map(x, 0, (height * 0.4), 128, 255); 
    let colVal02 = map(y, 0, (height * 0.4), 128, 255);
    let colVal03 = map(z, 0, (height * 0.4), 128, 255);
    
    //stroke(255, 255, 128);
    stroke(colVal01, colVal02, colVal03);
    
    point(x, y, z);
    
  }
 
  endShape();
 
}

seems to be roughly equivalent to https://github.com/mpwelton/lissajous/blob/main/Lissajous_Generator_FULL_VERSION.pde
